### ISSUE TITLE
Tetris Worlds PC

### ISSUE THREAD

**Issue by Nickelbawker** [dege-diosg/dgVoodoo2#26] opened 2020-11-07 22:40 UTC
Any chance of getting fixes for this? The game runs in a 800x600 window only on Win10 with borders in a ugly fullscreen manner. I got dgvoodoo to work for the most part boots the game right up, a lot of options cause the games cinematic after the logos to crash the game but I got passed that. Also two of the Worlds work decently it seems, haven't played them a lot yet. The multiplayer mode works pretty well too. The rest of the worlds either crash or show kind of a flickering of the stage and the GUI just before selecting the stage, depending on the settings. Game runs on dx8 and ddraw I believe. I also had it throw a direct 7 error during a crash. I can run the debug layer if you want, haven't downloaded that at the moment. The game doesn't crash without dgvoodoo but it's really ugly compared to running with dgvoodoo.

The PC release is pretty neat although if not I guess I could switch to PS2 version it seems pretty decent.

**Comment by dege-diosg** [comment] 2020-11-24 09:00
Indeed, it crashed randomly, I could reproduce it. I found something that wasn't compatible with MS DDraw (it's a D3D7 game btw), fixed it and now it seems to run without crashing. The fix will be included in the next version.

However I couldn't reproduce the GUI flickering. What's the easiest way to do that?

**Comment by Nickelbawker** [comment] 2020-11-24 22:16
GUI flickering was what happened when it didn't happen to crash occasionally with the exact same settings but waiting longer during each thing so I'm assuming this change will have fixed it as well.

**Comment by dege-diosg** [comment] 2020-12-12 14:13
Try v2.72, that should fix this problem (tested by me, it's working).

**Comment by Nickelbawker** [comment] 2020-12-14 05:53
Will give it a shot soon, setting up my first Arch install at the moment. Sounds sweet!

**Comment by dege-diosg** [comment] 2021-01-31 14:20
Closing this issue with: version 2.72 solved the problem.

**Closed by dege-diosg** 2021-01-31 14:20 UTC
